-- Migration: Event System and Actions
-- Description: Creates trigger, sensor, event, enforcement, and action tables
--              with runtime version constraint support. Includes webhook key
--              generation function used by webhook management functions in 000007.
--
--              NOTE: The event and enforcement tables are converted to TimescaleDB
--              hypertables in migration 000009. Hypertables cannot be the target of
--              FK constraints, so enforcement.event is a plain BIGINT with no FK.
--              FKs *from* hypertables to regular tables (e.g., event.trigger → trigger,
--              enforcement.rule → rule) are supported by TimescaleDB 2.x and are kept.
-- Version: 20250101000004

-- Set search_path for schema isolation
SET search_path TO attune, public;

-- ============================================================================
-- WEBHOOK KEY GENERATION
-- ============================================================================

DO $$ BEGIN
    CREATE TYPE action_reference_visibility_enum AS ENUM (
        'public',
        'private',
        'restricted'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

COMMENT ON TYPE action_reference_visibility_enum IS
    'Controls which packs may reference an action, trigger, or queue from pack-owned components';

-- Generates a unique webhook key in the format: wh_<32 random hex chars>
-- Used by enable_trigger_webhook() and regenerate_trigger_webhook_key() in 000007.
CREATE OR REPLACE FUNCTION generate_webhook_key()
RETURNS VARCHAR(64) AS $$
BEGIN
    RETURN 'wh_' || encode(gen_random_bytes(16), 'hex');
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_webhook_key() IS 'Generates a unique webhook key (format: wh_<32 hex chars>) for trigger webhook authentication';

-- ============================================================================
-- TRIGGER TABLE
-- ============================================================================

CREATE TABLE trigger (
    id BIGSERIAL PRIMARY KEY,
    ref TEXT NOT NULL UNIQUE,
    pack BIGINT REFERENCES pack(id) ON DELETE CASCADE,
    pack_ref TEXT,
    label TEXT NOT NULL,
    description TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_adhoc BOOLEAN DEFAULT false NOT NULL,
    param_schema JSONB,
    out_schema JSONB,
    webhook_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    webhook_key VARCHAR(64) UNIQUE,
    webhook_config JSONB DEFAULT '{}'::jsonb,
    sensor BIGINT,  -- FK added after sensor table is created
    sensor_ref TEXT,
    reference_visibility action_reference_visibility_enum NOT NULL DEFAULT 'public',
    reference_allowed_pack_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT trigger_ref_lowercase CHECK (ref = LOWER(ref)),
    CONSTRAINT trigger_ref_format CHECK (ref ~ '^[^.]+\.[^.]+$'),
    CONSTRAINT trigger_reference_allowed_pack_refs_non_null
        CHECK (array_position(reference_allowed_pack_refs, NULL) IS NULL),
    CONSTRAINT trigger_reference_allowed_pack_refs_restricted_only
        CHECK (reference_visibility = 'restricted' OR cardinality(reference_allowed_pack_refs) = 0)
);

-- Indexes
CREATE INDEX idx_trigger_ref ON trigger(ref);
CREATE INDEX idx_trigger_pack ON trigger(pack);
CREATE INDEX idx_trigger_enabled ON trigger(enabled) WHERE enabled = TRUE;
CREATE INDEX idx_trigger_created ON trigger(created DESC);
CREATE INDEX idx_trigger_pack_enabled ON trigger(pack, enabled);
CREATE INDEX idx_trigger_webhook_key ON trigger(webhook_key) WHERE webhook_key IS NOT NULL;
CREATE INDEX idx_trigger_enabled_created ON trigger(enabled, created DESC) WHERE enabled = TRUE;
CREATE INDEX idx_trigger_sensor ON trigger(sensor) WHERE sensor IS NOT NULL;
CREATE INDEX idx_trigger_reference_visibility ON trigger(reference_visibility);
CREATE INDEX idx_trigger_reference_allowed_pack_refs ON trigger USING GIN (reference_allowed_pack_refs);

-- Trigger
CREATE TRIGGER update_trigger_updated
    BEFORE UPDATE ON trigger
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_column();

-- Comments
COMMENT ON TABLE trigger IS 'Trigger definitions that can activate rules';
COMMENT ON COLUMN trigger.ref IS 'Unique trigger reference (format: pack.name)';
COMMENT ON COLUMN trigger.label IS 'Human-readable trigger name';
COMMENT ON COLUMN trigger.enabled IS 'Whether this trigger is active';
COMMENT ON COLUMN trigger.param_schema IS 'JSON schema defining the expected configuration parameters when this trigger is used';
COMMENT ON COLUMN trigger.out_schema IS 'JSON schema defining the structure of event payloads generated by this trigger';
COMMENT ON COLUMN trigger.reference_visibility IS 'Pack-level reference visibility: public triggers may be subscribed to by rules from any pack; private triggers only by rules in their owning pack; restricted triggers by their owning pack and reference_allowed_pack_refs.';
COMMENT ON COLUMN trigger.reference_allowed_pack_refs IS 'Allow-list of pack refs that may subscribe to this trigger when reference_visibility is restricted.';

-- ============================================================================
-- WEBHOOK EVENT LOG
-- ============================================================================

CREATE TABLE webhook_event_log (
    id BIGSERIAL PRIMARY KEY,
    trigger_id BIGINT NOT NULL REFERENCES trigger(id) ON DELETE CASCADE,
    trigger_ref TEXT NOT NULL,
    webhook_key VARCHAR(64) NOT NULL,
    event_id BIGINT,
    source_ip TEXT,
    user_agent TEXT,
    payload_size_bytes INTEGER,
    headers JSONB,
    status_code INTEGER NOT NULL,
    error_message TEXT,
    processing_time_ms INTEGER,
    hmac_verified BOOLEAN,
    rate_limited BOOLEAN NOT NULL DEFAULT FALSE,
    ip_allowed BOOLEAN,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_webhook_event_log_trigger_created ON webhook_event_log(trigger_id, created DESC);
CREATE INDEX idx_webhook_event_log_key_created ON webhook_event_log(webhook_key, created DESC);
CREATE INDEX idx_webhook_event_log_rate_limit ON webhook_event_log(trigger_id, webhook_key, source_ip, created DESC)
    WHERE rate_limited = FALSE;

COMMENT ON TABLE webhook_event_log IS 'Audit trail for webhook requests and security decisions';

-- ============================================================================


-- ============================================================================
-- SENSOR TABLE
-- ============================================================================

CREATE TABLE sensor (
    id BIGSERIAL PRIMARY KEY,
    ref TEXT NOT NULL UNIQUE,
    pack BIGINT REFERENCES pack(id) ON DELETE CASCADE,
    pack_ref TEXT,
    label TEXT NOT NULL,
    description TEXT,
    entrypoint TEXT NOT NULL,
    runtime BIGINT NOT NULL REFERENCES runtime(id) ON DELETE CASCADE,
    runtime_ref TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    is_adhoc BOOLEAN NOT NULL DEFAULT FALSE,
    param_schema JSONB,
    config JSONB,
    runtime_version_constraint TEXT,
    worker_selector JSONB NOT NULL DEFAULT '{}'::jsonb,
    worker_tolerations JSONB NOT NULL DEFAULT '[]'::jsonb,
    worker_affinity JSONB NOT NULL DEFAULT '{}'::jsonb,
    log_retention_policy artifact_retention_enum,
    log_retention_limit INTEGER,
    artifact_retention_policy artifact_retention_enum,
    artifact_retention_limit INTEGER,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT sensor_ref_lowercase CHECK (ref = LOWER(ref)),
    CONSTRAINT sensor_ref_format CHECK (ref ~ '^[^.]+\.[^.]+$'),
    CONSTRAINT sensor_log_retention_limit_positive CHECK (log_retention_limit IS NULL OR log_retention_limit > 0),
    CONSTRAINT sensor_artifact_retention_limit_positive CHECK (artifact_retention_limit IS NULL OR artifact_retention_limit > 0)
);

-- Indexes
CREATE INDEX idx_sensor_ref ON sensor(ref);
CREATE INDEX idx_sensor_pack ON sensor(pack);
CREATE INDEX idx_sensor_runtime ON sensor(runtime);
CREATE INDEX idx_sensor_enabled ON sensor(enabled) WHERE enabled = TRUE;
CREATE INDEX idx_sensor_is_adhoc ON sensor(is_adhoc) WHERE is_adhoc = true;
CREATE INDEX idx_sensor_created ON sensor(created DESC);
CREATE INDEX idx_sensor_worker_selector_gin ON sensor USING GIN (worker_selector);
CREATE INDEX idx_sensor_worker_tolerations_gin ON sensor USING GIN (worker_tolerations);
CREATE INDEX idx_sensor_worker_affinity_gin ON sensor USING GIN (worker_affinity);

-- Add FK from trigger.sensor → sensor(id) now that sensor table exists
ALTER TABLE trigger ADD CONSTRAINT trigger_sensor_fk FOREIGN KEY (sensor) REFERENCES sensor(id) ON DELETE SET NULL;

-- Trigger
CREATE TRIGGER update_sensor_updated
    BEFORE UPDATE ON sensor
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_column();

-- Comments
COMMENT ON TABLE sensor IS 'Sensors monitor for events and create trigger instances';
COMMENT ON COLUMN sensor.ref IS 'Unique sensor reference (format: pack.name)';
COMMENT ON COLUMN sensor.label IS 'Human-readable sensor name';
COMMENT ON COLUMN sensor.entrypoint IS 'Script or command to execute';
COMMENT ON COLUMN sensor.runtime IS 'Runtime environment for execution';
COMMENT ON COLUMN sensor.enabled IS 'Whether this sensor is active';
COMMENT ON COLUMN sensor.is_adhoc IS 'True if sensor was manually created (ad-hoc), false if installed from pack';
COMMENT ON COLUMN sensor.runtime_version_constraint IS 'Semver version constraint for the runtime (e.g., ">=3.12", ">=3.12,<4.0", "~18.0"). NULL means any version.';
COMMENT ON COLUMN sensor.worker_selector IS 'Exact sensor-worker label selector required to run this sensor';
COMMENT ON COLUMN sensor.worker_tolerations IS 'Tolerations allowing this sensor onto tainted sensor workers';
COMMENT ON COLUMN sensor.worker_affinity IS 'Required/preferred/anti-affinity placement rules for sensor workers';
COMMENT ON COLUMN sensor.log_retention_policy IS 'Optional per-sensor override for registered stdout/stderr log artifact retention policy. NULL inherits the service default.';
COMMENT ON COLUMN sensor.log_retention_limit IS 'Optional per-sensor override for registered stdout/stderr log artifact retention limit. NULL inherits the service default.';
COMMENT ON COLUMN sensor.artifact_retention_policy IS 'Optional per-sensor default retention policy for non-log artifacts created by this sensor. NULL uses API defaults.';
COMMENT ON COLUMN sensor.artifact_retention_limit IS 'Optional per-sensor default retention limit for non-log artifacts created by this sensor. NULL uses API defaults.';

-- ============================================================================
-- EVENT TABLE
-- ============================================================================

CREATE TABLE event (
    id BIGSERIAL PRIMARY KEY,
    trigger BIGINT REFERENCES trigger(id) ON DELETE SET NULL,
    trigger_ref TEXT NOT NULL,
    config JSONB,
    payload JSONB,
    source BIGINT REFERENCES sensor(id) ON DELETE SET NULL,
    source_ref TEXT,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rule BIGINT,
    rule_ref TEXT
);

-- Indexes
CREATE INDEX idx_event_trigger ON event(trigger);
CREATE INDEX idx_event_trigger_ref ON event(trigger_ref);
CREATE INDEX idx_event_source ON event(source);
CREATE INDEX idx_event_created ON event(created DESC);
CREATE INDEX idx_event_trigger_created ON event(trigger, created DESC);
CREATE INDEX idx_event_trigger_ref_created ON event(trigger_ref, created DESC);
CREATE INDEX idx_event_source_created ON event(source, created DESC);
CREATE INDEX idx_event_payload_gin ON event USING GIN (payload);

-- Comments
COMMENT ON TABLE event IS 'Events are instances of triggers firing';
COMMENT ON COLUMN event.trigger IS 'Trigger that fired (may be null if trigger deleted)';
COMMENT ON COLUMN event.trigger_ref IS 'Trigger reference (preserved even if trigger deleted)';
COMMENT ON COLUMN event.config IS 'Snapshot of trigger/sensor configuration at event time';
COMMENT ON COLUMN event.payload IS 'Event data payload';
COMMENT ON COLUMN event.source IS 'Sensor that generated this event';

-- ============================================================================
-- ENFORCEMENT TABLE
-- ============================================================================

CREATE TABLE enforcement (
    id BIGSERIAL PRIMARY KEY,
    rule BIGINT, -- Forward reference to rule table, will add constraint after rule is created
    rule_ref TEXT NOT NULL,
    trigger_ref TEXT NOT NULL,
    config JSONB,
    event BIGINT,           -- references event(id); no FK because event becomes a hypertable
    status enforcement_status_enum NOT NULL DEFAULT 'created',
    payload JSONB NOT NULL,
    condition enforcement_condition_enum NOT NULL DEFAULT 'all',
    conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,

    -- Constraints
    CONSTRAINT enforcement_condition_check CHECK (condition IN ('any', 'all'))
);

-- Indexes
CREATE INDEX idx_enforcement_rule ON enforcement(rule);
CREATE INDEX idx_enforcement_rule_ref ON enforcement(rule_ref);
CREATE INDEX idx_enforcement_trigger_ref ON enforcement(trigger_ref);
CREATE INDEX idx_enforcement_event ON enforcement(event);
CREATE INDEX idx_enforcement_status ON enforcement(status);
CREATE INDEX idx_enforcement_created ON enforcement(created DESC);
CREATE INDEX idx_enforcement_status_created ON enforcement(status, created DESC);
CREATE INDEX idx_enforcement_rule_status ON enforcement(rule, status);
CREATE INDEX idx_enforcement_event_status ON enforcement(event, status);
CREATE INDEX idx_enforcement_payload_gin ON enforcement USING GIN (payload);
CREATE INDEX idx_enforcement_conditions_gin ON enforcement USING GIN (conditions);
CREATE UNIQUE INDEX uq_enforcement_rule_event
    ON enforcement (rule, event)
    WHERE rule IS NOT NULL AND event IS NOT NULL;

-- Comments
COMMENT ON TABLE enforcement IS 'Enforcements represent rule triggering by events';
COMMENT ON COLUMN enforcement.rule IS 'Rule being enforced (may be null if rule deleted)';
COMMENT ON COLUMN enforcement.rule_ref IS 'Rule reference (preserved even if rule deleted)';
COMMENT ON COLUMN enforcement.event IS 'Event that triggered this enforcement (no FK — event is a hypertable)';
COMMENT ON COLUMN enforcement.status IS 'Processing status (created → processed or disabled)';
COMMENT ON COLUMN enforcement.resolved_at IS 'Timestamp when the enforcement was resolved (status changed from created to processed/disabled). NULL while status is created.';
COMMENT ON COLUMN enforcement.payload IS 'Event payload for rule evaluation';
COMMENT ON COLUMN enforcement.condition IS 'Logical operator for conditions (any=OR, all=AND)';
COMMENT ON COLUMN enforcement.conditions IS 'Condition expressions to evaluate';

-- ============================================================================
-- ACTION TABLE
-- ============================================================================

CREATE TABLE action (
    id BIGSERIAL PRIMARY KEY,
    ref TEXT NOT NULL UNIQUE,
    pack BIGINT NOT NULL REFERENCES pack(id) ON DELETE CASCADE,
    pack_ref TEXT NOT NULL,
    label TEXT NOT NULL,
    description TEXT,
    entrypoint TEXT NOT NULL,
    runtime BIGINT REFERENCES runtime(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    param_schema JSONB,
    out_schema JSONB,
    parameter_delivery TEXT NOT NULL DEFAULT 'stdin' CHECK (parameter_delivery IN ('stdin', 'file')),
    parameter_format TEXT NOT NULL DEFAULT 'json' CHECK (parameter_format IN ('dotenv', 'json', 'yaml')),
    output_format TEXT NOT NULL DEFAULT 'text' CHECK (output_format IN ('text', 'json', 'yaml', 'jsonl')),
    is_adhoc BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_seconds INTEGER,
    max_retries INTEGER DEFAULT 0,
    runtime_version_constraint TEXT,
    accesses_mcp BOOLEAN NOT NULL DEFAULT FALSE,
    default_execution_permission_set_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    reference_visibility action_reference_visibility_enum NOT NULL DEFAULT 'public',
    reference_allowed_pack_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    log_retention_policy artifact_retention_enum,
    log_retention_limit INTEGER,
    artifact_retention_policy artifact_retention_enum,
    artifact_retention_limit INTEGER,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT action_ref_lowercase CHECK (ref = LOWER(ref)),
    CONSTRAINT action_ref_format CHECK (ref ~ '^[^.]+\.[^.]+$'),
    CONSTRAINT action_log_retention_limit_positive CHECK (log_retention_limit IS NULL OR log_retention_limit > 0),
    CONSTRAINT action_artifact_retention_limit_positive CHECK (artifact_retention_limit IS NULL OR artifact_retention_limit > 0),
    CONSTRAINT action_timeout_seconds_positive CHECK (timeout_seconds IS NULL OR timeout_seconds > 0),
    CONSTRAINT action_reference_allowed_pack_refs_non_null
        CHECK (array_position(reference_allowed_pack_refs, NULL) IS NULL),
    CONSTRAINT action_reference_allowed_pack_refs_restricted_only
        CHECK (reference_visibility = 'restricted' OR cardinality(reference_allowed_pack_refs) = 0)
);

-- Indexes
CREATE INDEX idx_action_ref ON action(ref);
CREATE INDEX idx_action_pack ON action(pack);
CREATE INDEX idx_action_runtime ON action(runtime);
CREATE INDEX idx_action_enabled ON action(enabled);
CREATE INDEX idx_action_parameter_delivery ON action(parameter_delivery);
CREATE INDEX idx_action_parameter_format ON action(parameter_format);
CREATE INDEX idx_action_output_format ON action(output_format);
CREATE INDEX idx_action_is_adhoc ON action(is_adhoc) WHERE is_adhoc = true;
CREATE INDEX idx_action_accesses_mcp ON action(accesses_mcp) WHERE accesses_mcp = true;
CREATE INDEX idx_action_default_execution_permission_set_refs ON action USING GIN (default_execution_permission_set_refs);
CREATE INDEX idx_action_reference_visibility ON action(reference_visibility);
CREATE INDEX idx_action_reference_allowed_pack_refs ON action USING GIN (reference_allowed_pack_refs);
CREATE INDEX idx_action_created ON action(created DESC);

-- Trigger
CREATE TRIGGER update_action_updated
    BEFORE UPDATE ON action
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_column();

-- Comments
COMMENT ON TABLE action IS 'Actions are executable tasks that can be triggered';
COMMENT ON COLUMN action.ref IS 'Unique action reference (format: pack.name)';
COMMENT ON COLUMN action.pack IS 'Pack this action belongs to';
COMMENT ON COLUMN action.label IS 'Human-readable action name';
COMMENT ON COLUMN action.entrypoint IS 'Script or command to execute';
COMMENT ON COLUMN action.runtime IS 'Runtime environment for execution';
COMMENT ON COLUMN action.param_schema IS 'JSON schema for action parameters';
COMMENT ON COLUMN action.out_schema IS 'JSON schema for action output';
COMMENT ON COLUMN action.parameter_delivery IS 'How parameters are delivered: stdin (standard input - secure), file (temporary file - secure for large payloads). Environment variables are set separately via execution.env_vars.';
COMMENT ON COLUMN action.parameter_format IS 'Parameter serialization format: json (JSON object - default), dotenv (KEY=''VALUE''), yaml (YAML format)';
COMMENT ON COLUMN action.output_format IS 'Output parsing format: text (no parsing - raw stdout), json (parse stdout as JSON), yaml (parse stdout as YAML), jsonl (parse each line as JSON, collect into array)';
COMMENT ON COLUMN action.is_adhoc IS 'True if action was manually created (ad-hoc), false if installed from pack';
COMMENT ON COLUMN action.timeout_seconds IS 'Default execution timeout in seconds for this action. Snapshotted onto execution.timeout_seconds at execution creation time. If NULL, the app-level default_execution_timeout_seconds config is used.';
COMMENT ON COLUMN action.max_retries IS 'Maximum number of automatic retry attempts for failed executions. 0 = no retries (default).';
COMMENT ON COLUMN action.runtime_version_constraint IS 'Semver version constraint for the runtime (e.g., ">=3.12", ">=3.12,<4.0", "~18.0"). NULL means any version.';
COMMENT ON COLUMN action.accesses_mcp IS 'Hint that this action may invoke the Attune MCP server (e.g., AI agent actions). When true, executions of this action may have child executions spawned via execution-scoped tokens; consumers (UI, CLI, timeline charts) can use this flag to optimistically render subtask views without waiting for children to appear.';
COMMENT ON COLUMN action.default_execution_permission_set_refs IS 'Permission set refs applied to execution-scoped API tokens when executions do not explicitly override them. Empty means no execution API token is exposed to the action.';
COMMENT ON COLUMN action.reference_visibility IS 'Pack-level reference visibility: public actions may be referenced by any pack; private actions only by their owning pack; restricted actions by their owning pack and reference_allowed_pack_refs.';
COMMENT ON COLUMN action.reference_allowed_pack_refs IS 'Allow-list of pack refs that may reference this action when reference_visibility is restricted.';
COMMENT ON COLUMN action.log_retention_policy IS 'Optional per-action override for stdout/stderr execution log artifact retention policy. NULL inherits worker.execution_log_retention_policy.';
COMMENT ON COLUMN action.log_retention_limit IS 'Optional per-action override for stdout/stderr execution log artifact retention limit. NULL inherits worker.execution_log_retention_limit.';
COMMENT ON COLUMN action.artifact_retention_policy IS 'Optional per-action default retention policy for non-log artifacts created by executions of this action. NULL uses API defaults.';
COMMENT ON COLUMN action.artifact_retention_limit IS 'Optional per-action default retention limit for non-log artifacts created by executions of this action. NULL uses API defaults.';

-- ============================================================================

-- Add foreign key constraint for policy table
ALTER TABLE policy
    ADD CONSTRAINT policy_action_fkey
    FOREIGN KEY (action) REFERENCES action(id) ON DELETE CASCADE;

-- Note: Foreign key constraints for key table (key_owner_action_fkey, key_owner_sensor_fkey)
-- will be added in migration 000007_supporting_systems.sql after the key table is created

-- Note: Rule table will be created in migration 000005 after execution table exists
-- Note: Foreign key constraints for enforcement.rule and event.rule will be added there

-- ============================================================================
-- EVENT / ENFORCEMENT NOTIFICATIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION notify_event_created()
RETURNS TRIGGER AS $$
DECLARE
    payload JSON;
BEGIN
    payload := json_build_object(
        'entity_type', 'event',
        'entity_id', NEW.id,
        'id', NEW.id,
        'trigger', NEW.trigger,
        'trigger_ref', NEW.trigger_ref,
        'source', NEW.source,
        'source_ref', NEW.source_ref,
        'rule', NEW.rule,
        'rule_ref', NEW.rule_ref,
        'has_payload', NEW.payload IS NOT NULL,
        'created', NEW.created
    );

    PERFORM pg_notify('event_created', payload::text);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER event_created_notify
    AFTER INSERT ON event
    FOR EACH ROW
    EXECUTE FUNCTION notify_event_created();

COMMENT ON FUNCTION notify_event_created() IS 'Sends event creation notifications via PostgreSQL LISTEN/NOTIFY';

CREATE OR REPLACE FUNCTION notify_enforcement_created()
RETURNS TRIGGER AS $$
DECLARE
    payload JSON;
BEGIN
    payload := json_build_object(
        'entity_type', 'enforcement',
        'entity_id', NEW.id,
        'id', NEW.id,
        'rule', NEW.rule,
        'rule_ref', NEW.rule_ref,
        'trigger_ref', NEW.trigger_ref,
        'event', NEW.event,
        'status', NEW.status,
        'condition', NEW.condition,
        'created', NEW.created,
        'resolved_at', NEW.resolved_at
    );

    PERFORM pg_notify('enforcement_created', payload::text);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforcement_created_notify
    AFTER INSERT ON enforcement
    FOR EACH ROW
    EXECUTE FUNCTION notify_enforcement_created();

COMMENT ON FUNCTION notify_enforcement_created() IS 'Sends enforcement creation notifications via PostgreSQL LISTEN/NOTIFY';

CREATE OR REPLACE FUNCTION notify_enforcement_status_changed()
RETURNS TRIGGER AS $$
DECLARE
    payload JSON;
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
        payload := json_build_object(
            'entity_type', 'enforcement',
            'entity_id', NEW.id,
            'id', NEW.id,
            'rule', NEW.rule,
            'rule_ref', NEW.rule_ref,
            'trigger_ref', NEW.trigger_ref,
            'event', NEW.event,
            'status', NEW.status,
            'old_status', OLD.status,
            'condition', NEW.condition,
            'created', NEW.created,
            'resolved_at', NEW.resolved_at
        );

        PERFORM pg_notify('enforcement_status_changed', payload::text);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforcement_status_changed_notify
    AFTER UPDATE ON enforcement
    FOR EACH ROW
    EXECUTE FUNCTION notify_enforcement_status_changed();

COMMENT ON FUNCTION notify_enforcement_status_changed() IS 'Sends enforcement status change notifications via PostgreSQL LISTEN/NOTIFY';
