/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { i64 } from "./i64";
/**
 * Standard API response wrapper
 */
export type ApiResponse_EventResponse = {
  /**
   * Full event response with all details
   */
  data: {
    /**
     * Event configuration
     */
    config: any | null;
    /**
     * Creation timestamp
     */
    created: string;
    /**
     * Event ID
     */
    id: i64;
    /**
     * Event payload data
     */
    payload: Record<string, any>;
    rule?: null | i64;
    /**
     * Rule reference (if event was generated by a specific rule)
     */
    rule_ref?: string | null;
    source?: null | i64;
    /**
     * Source reference
     */
    source_ref?: string | null;
    trigger?: null | i64;
    /**
     * Trigger reference
     */
    trigger_ref: string;
  };
  /**
   * Optional message
   */
  message?: string | null;
};
