import {
  CircleArrowRight,
  CircleDot,
  CirclePlay,
  DatabaseZap,
  FolderArchive,
  Home,
  KeyRound,
  Package,
  Gauge,
  Search,
  ShieldCheck,
  ScrollText,
  SquareArrowRight,
  SquareAsterisk,
  SquareDot,
  SquarePlay,
  SquareStack,
  TerminalSquare,
} from "lucide-react";

export const navIcons = {
  dashboard: Home,
  actions: SquarePlay,
  runtimes: TerminalSquare,
  rules: SquareArrowRight,
  triggers: SquareDot,
  sensors: SquareAsterisk,
  executions: CirclePlay,
  enforcements: CircleArrowRight,
  events: CircleDot,
  keys: KeyRound,
  artifacts: FolderArchive,
  queues: SquareStack,
  policies: Gauge,
  accessControl: ShieldCheck,
  auditLog: ScrollText,
  retention: DatabaseZap,
  packs: Package,
  traces: Search,
} as const;
